name       : haskell-filelock
version    : 0.1.1.4
release    : 3
source     :
    - https://hackage.haskell.org/package/filelock-0.1.1.4/filelock-0.1.1.4.tar.gz : d97e29095b0d8b652bc02e52d79bb415e75285c651bcaacb108db883f72536a1
license    : CC0-1.0
component  : programming.haskell
summary    : This package provides an interface to Windows and Unix file locking functionalities.
description: |
    This package provides an interface to Windows and Unix file locking functionalities.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
