name       : haskell-filelock
version    : 0.1.1.2
release    : 2
source     :
    - https://hackage.haskell.org/package/filelock-0.1.1.2/filelock-0.1.1.2.tar.gz : 0ff1dcb13ec619f72496035e2a1298ef9dc6a814ba304d882cd9b145eae3203d
license    : CC0-1.0
component  : programming.haskell
summary    : This package provides an interface to Windows and Unix file locking functionalities.
description: |
    This package provides an interface to Windows and Unix file locking functionalities.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
