name       : haskell-filelock
version    : 0.1.0.1
release    : 1
source     :
    - http://hackage.haskell.org/package/filelock-0.1.0.1/filelock-0.1.0.1.tar.gz : ad8c63f27fec6396ac83981a67d5a799b6b614c119a35ebdf2d82b379795d763
license    : CC0-1.0
component  : programming.haskell
summary    : This package provides an interface to Windows and Unix file locking functionalities.
description: |
    This package provides an interface to Windows and Unix file locking functionalities.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
